// features/offerApi.ts
import { createApi } from "@reduxjs/toolkit/query/react";
import baseQueryWithReauth from "./baseQueryWithReauth";

// =============================
// REQUEST TYPES
// =============================

export interface CreateOfferRequest {
  title: string;
  description?: string;
  type: OfferType;
  category?: OfferCategoryType;
  discountType: DiscountType;
  discountValue: number;
  maxDiscountAmount?: number;
  minOrderAmount?: number;
  validFrom: string | Date;
  validTo?: string | Date;
  totalUsageLimit?: number;
  userUsageLimit?: number;
  isPublic?: boolean;
  applicableToAll?: boolean;
  bannerImage?: string;
  termsAndConditions?: string;
  priority?: number;
  status?: OfferStatus;
  targetProductIds?: string[];
  targetCategoryIds?: string[];
  targetVendorIds?: string[];
  targetUserIds?: string[];
  countdownConfig?: CountdownOfferConfig;
  voucherConfig?: VoucherOfferConfig;
  buyXGetYConfig?: BuyXGetYOfferConfig;
  stackRuleConfig?: OfferStackRuleConfig;
}

export interface CountdownOfferConfig {
  originalPrice?: number;
  flashPrice?: number;
  quantityLimit?: number;
  countdownEnds: string | Date;
  urgencyText?: string;
  scarcityText?: string;
  showCountdown?: boolean;
}

export interface VoucherOfferConfig {
  code?: string;
  isPublic?: boolean;
  requiresCode?: boolean;
  firstTimeOnly?: boolean;
  isAutoGenerated?: boolean;
}

export interface BuyXGetYOfferConfig {
  buyProductId: string;
  getProductId: string;
  buyQuantity?: number;
  getQuantity?: number;
}

export interface OfferStackRuleConfig {
  canCombineWithOtherOffers?: boolean;
  maxStackCount?: number;
}

export interface CreateFlashSaleRequest {
  title: string;
  productIds: string[];
  originalPrice: number;
  flashPrice: number;
  quantityLimit: number;
  duration: number;
  urgencyText?: string;
}

export interface CreateSystemVoucherRequest {
  title: string;
  code: string;
  discountType: DiscountType;
  discountValue: number;
  maxDiscountAmount?: number;
  minOrderAmount?: number;
  validFrom: string | Date;
  validTo: string | Date;
  usageLimit?: number;
  userUsageLimit?: number;
  firstTimeOnly?: boolean;
}

export interface CreateVendorVoucherRequest {
  title: string;
  code?: string;
  discountType: DiscountType;
  discountValue: number;
  minOrderAmount?: number;
  validFrom: string | Date;
  validTo: string | Date;
  usageLimit?: number;
  userUsageLimit?: number;
  productIds?: string[];
}

export interface ApplyVoucherRequest {
  code: string;
  orderData: {
    items: OrderItem[];
    subtotal: number;
    vendorId?: string;
  };
}

export interface ValidateOfferRequest {
  offerId: string;
  orderData: {
    items: OrderItem[];
    subtotal: number;
  };
}

export interface RecordOfferUsageRequest {
  offerId: string;
  userId: string;
  orderId?: number;
  discountApplied: number;
  orderAmount: number;
}

export interface ApproveOfferRequest {
  approved: boolean;
}

export interface OrderItem {
  productId: string;
  quantity: number;
  price: number;
  vendorId?: string;
}

// =============================
// PERMISSION MANAGEMENT TYPES
// =============================

export interface VendorPermissionFilters {
  vendorId?: string;
  vendorName?: string;
  page?: number;
  limit?: number;
}

export interface VendorPermissionStats {
  totalVendors: number;
  vendorsWithPermissions: number;
  canCreateFlashSale: number;
  requiresApproval: number;
  averageMaxDiscount: number;
}

export interface BulkUpdatePermissionsRequest {
  vendorIds: string[];
  canCreateRegular?: boolean;
  canCreateVoucher?: boolean;
  canCreateCountdown?: boolean;
  canCreateFlashSale?: boolean;
  maxDiscountPercent?: number;
  maxDiscountAmount?: number;
  maxActiveOffers?: number;
  requiresApproval?: boolean;
}

export interface BulkUpdatePermissionsResponse {
  updated: number;
  failed: string[];
}

export interface VendorWithPermissions extends VendorPermissions {
  vendor?: {
    id: string;
    user?: {
      id: string;
      name: string;
      email: string;
      avatar?: string;
    };
    storeName?: string;
    _count?: {
      offers: number;
    };
  };
}

export interface UpdateVendorPermissionsRequest {
  canCreateRegular?: boolean;
  canCreateVoucher?: boolean;
  canCreateCountdown?: boolean;
  canCreateFlashSale?: boolean;
  canCreateBuyXGetY?: boolean;
  canCreateFreeShipping?: boolean;
  canCreateBundleDeal?: boolean;
  canCreateSeasonalSale?: boolean;
  canCreateLoyaltyReward?: boolean;
  canCreateReferralBonus?: boolean;
  maxDiscountPercent?: number;
  maxDiscountAmount?: number;
  maxActiveOffers?: number;
  maxVouchersPerOffer?: number;
  maxFlashSaleDuration?: number;
  maxBundleItems?: number;
  requiresApproval?: boolean;
}

// =============================
// REPORTING TYPES
// =============================

export interface OfferPerformanceFilters {
  startDate?: string;
  endDate?: string;
  offerType?: OfferType;
  vendorId?: string;
}

export interface TopPerformingOffersFilters {
  limit?: number;
  vendorId?: string;
  startDate?: string;
  endDate?: string;
}

export interface OfferPerformanceReport {
  id: string;
  title: string;
  type: OfferType;
  status: OfferStatus;
  createdBy: string;
  totalUsage: number;
  totalRevenue: number;
  totalDiscount: number;
  totalViews: number;
  totalClicks: number;
  conversionRate: number;
  avgOrderValue: number;
  roi: number;
}

export interface VendorOffersSummary {
  totalOffers: number;
  activeOffers: number;
  pendingOffers: number;
  approvedOffers: number;
  rejectedOffers: number;
  totalUsage: number;
  totalRevenue: number;
  totalDiscount: number;
}

export interface OfferUsageStats {
  totalUsage: number;
  uniqueUsers: number;
  totalRevenue: number;
  avgOrderValue: number;
  totalDiscount: number;
}

// =============================
// QUERY PARAMS
// =============================

export interface OfferFilters {
  type?: OfferType;
  status?: OfferStatus;
  isActive?: boolean;
  createdByType?: CreatorType;
  vendorId?: string;
  categoryId?: string;
  page?: number;
  limit?: number;
}

export interface AnalyticsQuery {
  startDate?: string;
  endDate?: string;
}

export interface UsageHistoryFilters {
  offerId?: string;
  page?: number;
  limit?: number;
}

// =============================
// ENUM TYPES
// =============================

export type OfferType =
  | "REGULAR_DISCOUNT"
  | "VOUCHER"
  | "COUNTDOWN_DEAL"
  | "FLASH_SALE"
  | "BUY_X_GET_Y"
  | "FREE_SHIPPING"
  | "BUNDLE_DEAL"
  | "SEASONAL_SALE"
  | "LOYALTY_REWARD"
  | "REFERRAL_BONUS";

export type OfferStatus =
  | "PENDING"
  | "APPROVED"
  | "REJECTED"
  | "ACTIVE"
  | "EXPIRED"
  | "PAUSED";

export type OfferCategoryType =
  | "GENERAL"
  | "ELECTRONICS"
  | "FASHION"
  | "HOME_GARDEN"
  | "SPORTS"
  | "BEAUTY"
  | "FOOD_BEVERAGE"
  | "BOOKS"
  | "TOYS"
  | "AUTOMOTIVE"
  | "HEALTH"
  | "PETS";

export type DiscountType =
  | "PERCENTAGE"
  | "FIXED_AMOUNT"
  | "FREE_SHIPPING"
  | "BUY_X_GET_Y";

export type CreatorType = "ADMIN" | "VENDOR" | "SYSTEM";

// =============================
// RESPONSE TYPES
// =============================

export interface Offer {
  id: string;
  title: string;
  description?: string;
  slug: string;
  type: OfferType;
  category: OfferCategoryType;
  status: OfferStatus;
  discountType: DiscountType;
  discountValue: number;
  maxDiscountAmount?: number;
  minOrderAmount?: number;
  validFrom: string;
  validTo?: string;
  totalUsageLimit?: number;
  userUsageLimit?: number;
  currentUsageCount: number;
  isPublic: boolean;
  isActive: boolean;
  applicableToAll: boolean;
  bannerImage?: string;
  termsAndConditions?: string;
  priority: number;
  createdByType: CreatorType;
  createdAt: string;
  updatedAt: string;
  countdownConfig?: CountdownConfig;
  voucherConfig?: VoucherConfig;
  buyXGetYOffer?: BuyXGetYOffer;
  offerStackRules?: OfferStackRules;
  targetProducts?: TargetProduct[];
  targetCategories?: TargetCategory[];
  targetVendors?: TargetVendor[];
  targetUsers?: TargetUser[];
  usageHistory?: OfferUsage[];
  analytics?: OfferAnalytics[];
  createdByUser?: any;
  createdByVendor?: any;
}

export interface CountdownConfig {
  id: string;
  originalPrice?: number;
  flashPrice?: number;
  quantityLimit?: number;
  remainingQty?: number;
  countdownEnds: string;
  showCountdown: boolean;
  urgencyText?: string;
  scarcityText?: string;
}

export interface VoucherConfig {
  id: string;
  code: string;
  isPublic: boolean;
  requiresCode: boolean;
  firstTimeOnly: boolean;
  isAutoGenerated: boolean;
}

export interface BuyXGetYOffer {
  id: string;
  offerId: string;
  buyProductId: string;
  getProductId: string;
  buyQuantity: number;
  getQuantity: number;
  buyProduct?: any;
  getProduct?: any;
}

export interface OfferStackRules {
  id: string;
  offerId: string;
  canCombineWithOtherOffers: boolean;
  maxStackCount: number;
}

export interface TargetProduct {
  id: string;
  productId: string;
  product?: any;
}

export interface TargetCategory {
  id: string;
  categoryId: string;
  category?: any;
}

export interface TargetVendor {
  id: string;
  vendorId: string;
  vendor?: any;
}

export interface TargetUser {
  id: string;
  userId: string;
  user?: any;
}

export interface OfferUsage {
  id: string;
  offerId: string;
  userId: string;
  orderId?: number;
  discountApplied: number;
  orderAmount: number;
  usedAt: string;
  user?: any;
  offer?: Offer;
  order?: any;
}

export interface OfferAnalytics {
  id: string;
  offerId: string;
  recordDate: string;
  totalUsage: number;
  totalRevenue: number;
  totalViews: number;
  totalClicks: number;
  uniqueUsers?: number;
  conversionRate?: number;
  avgOrderValue?: number;
}

export interface VendorPermissions {
  id: string;
  vendorId: string;
  
  // Basic offer type permissions
  canCreateRegular: boolean;
  canCreateVoucher: boolean;
  canCreateCountdown: boolean;
  canCreateFlashSale: boolean;
  canCreateBuyXGetY: boolean;
  canCreateFreeShipping: boolean;
  canCreateBundleDeal: boolean;
  canCreateSeasonalSale: boolean;
  canCreateLoyaltyReward: boolean;
  canCreateReferralBonus: boolean;
  
  // Global limits
  maxDiscountPercent: number;
  maxDiscountAmount: number;
  maxActiveOffers: number;
  
  // Type-specific limits
  maxVouchersPerOffer?: number;
  maxFlashSaleDuration?: number;
  maxBundleItems?: number;
  
  requiresApproval: boolean;
  createdAt?: string;
  updatedAt?: string;
}


export interface ApplyVoucherResponse {
  voucher: Offer;
  discount: number;
  applicableItems: OrderItem[];
  message: string;
}

export interface ValidateOfferResponse {
  valid: boolean;
  offer: Offer;
  discount?: number;
}

export interface ApiResponse<T> {
  success: boolean;
  message?: string;
  data?: T;
  errors?: Array<{ field: string; message: string }>;
}

export interface PaginatedResponse<T> {
  success: boolean;
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
  };
}

// =============================
// OFFER API
// =============================

export const offerApi = createApi({
  reducerPath: "offerApi",
  baseQuery: baseQueryWithReauth,
  tagTypes: [
    "Offer", 
    "VendorOffer", 
    "PublicOffer", 
    "Analytics", 
    "Permissions", 
    "VendorPermissions",
    "UsageHistory",
    "Reports"
  ],
  endpoints: (builder) => ({
    // =============================
    // PUBLIC ENDPOINTS
    // =============================
    
    getPublicOffers: builder.query<PaginatedResponse<Offer>, OfferFilters>({
      query: (params) => ({
        url: "/offers/public",
        method: "GET",
        params,
      }),
      providesTags: ["PublicOffer"],
    }),

    getFlashSales: builder.query<ApiResponse<Offer[]>, void>({
      query: () => ({
        url: "/offers/public/flash-sales",
        method: "GET",
      }),
      providesTags: ["PublicOffer"],
    }),

    getBuyXGetYOffers: builder.query<ApiResponse<Offer[]>, void>({
      query: () => ({
        url: "/offers/public/buy-x-get-y",
        method: "GET",
      }),
      providesTags: ["PublicOffer"],
    }),

    // =============================
    // ADMIN ENDPOINTS - OFFER MANAGEMENT
    // =============================

    // In your offerApi.ts, update the createOffer mutation:

createOffer: builder.mutation<ApiResponse<Offer>, FormData>({
  query: (formData) => ({
    url: "/offers/admin",
    method: "POST",
    body: formData,
    // Remove Content-Type header to let browser set it with boundary
    headers: {
      // Don't set Content-Type here - let the browser set it automatically for FormData
    },
  }),
  invalidatesTags: ["Offer", "PublicOffer"],
}),

    getAllOffers: builder.query<PaginatedResponse<Offer>, OfferFilters>({
      query: (params) => ({
        url: "/offers/admin",
        method: "GET",
        params,
      }),
      providesTags: ["Offer"],
    }),

    getOfferById: builder.query<ApiResponse<Offer>, string>({
      query: (offerId) => ({
        url: `/offers/admin/${offerId}`,
        method: "GET",
      }),
      providesTags: (result, error, id) => [{ type: "Offer", id }],
    }),

    updateOffer: builder.mutation<
      ApiResponse<Offer>,
      { offerId: string; data: Partial<CreateOfferRequest> }
    >({
      query: ({ offerId, data }) => ({
        url: `/offers/admin/${offerId}`,
        method: "PUT",
        body: data,
      }),
      invalidatesTags: (result, error, { offerId }) => [
        { type: "Offer", id: offerId },
        "Offer",
        "PublicOffer",
      ],
    }),

    deleteOffer: builder.mutation<ApiResponse<{ message: string }>, string>({
      query: (offerId) => ({
        url: `/offers/admin/${offerId}`,
        method: "DELETE",
      }),
      invalidatesTags: ["Offer", "PublicOffer"],
    }),

    createFlashSale: builder.mutation<ApiResponse<Offer>, CreateFlashSaleRequest>({
      query: (body) => ({
        url: "/offers/admin/flash-sale",
        method: "POST",
        body,
      }),
      invalidatesTags: ["Offer", "PublicOffer"],
    }),

    createSystemVoucher: builder.mutation<ApiResponse<Offer>, CreateSystemVoucherRequest>({
      query: (body) => ({
        url: "/offers/admin/system-voucher",
        method: "POST",
        body,
      }),
      invalidatesTags: ["Offer", "PublicOffer"],
    }),

    approveVendorOffer: builder.mutation<
      ApiResponse<Offer>,
      { offerId: string; approved: boolean }
    >({
      query: ({ offerId, approved }) => ({
        url: `/offers/admin/${offerId}/approve`,
        method: "PATCH",
        body: { approved },
      }),
      invalidatesTags: (result, error, { offerId }) => [
        { type: "Offer", id: offerId },
        "Offer",
        "VendorOffer",
      ],
    }),

    getOfferAnalytics: builder.query<
      ApiResponse<OfferAnalytics[]>,
      { offerId: string } & AnalyticsQuery
    >({
      query: ({ offerId, ...params }) => ({
        url: `/offers/admin/analytics/${offerId}`,
        method: "GET",
        params,
      }),
      providesTags: ["Analytics"],
    }),

    getAllOfferAnalytics: builder.query<
      ApiResponse<OfferAnalytics[]>,
      AnalyticsQuery
    >({
      query: (params) => ({
        url: "/offers/admin/analytics",
        method: "GET",
        params,
      }),
      providesTags: ["Analytics"],
    }),

    // =============================
    // ADMIN ENDPOINTS - VENDOR PERMISSION MANAGEMENT
    // =============================

    getAllVendorPermissions: builder.query<
      PaginatedResponse<VendorWithPermissions>,
      VendorPermissionFilters
    >({
      query: (params) => ({
        url: "/offers/admin/vendor-permissions",
        method: "GET",
        params,
      }),
      providesTags: ["VendorPermissions"],
    }),

    getVendorPermissionStats: builder.query<
      ApiResponse<VendorPermissionStats>,
      void
    >({
      query: () => ({
        url: "/offers/admin/vendor-permissions/stats",
        method: "GET",
      }),
      providesTags: ["VendorPermissions"],
    }),

    searchVendorsForPermissions: builder.query<
      ApiResponse<VendorWithPermissions[]>,
      { query: string; limit?: number }
    >({
      query: ({ query, limit }) => ({
        url: "/offers/admin/vendor-permissions/search",
        method: "GET",
        params: { query, limit },
      }),
    }),

    getVendorPermissions: builder.query<
      ApiResponse<VendorWithPermissions>,
      string
    >({
      query: (vendorId) => ({
        url: `/offers/admin/vendor-permissions/${vendorId}`,
        method: "GET",
      }),
      providesTags: (result, error, vendorId) => [
        { type: "VendorPermissions", id: vendorId }
      ],
    }),

    updateVendorPermissions: builder.mutation<
      ApiResponse<VendorPermissions>,
      { vendorId: string; data: UpdateVendorPermissionsRequest }
    >({
      query: ({ vendorId, data }) => ({
        url: `/offers/admin/vendor-permissions/${vendorId}`,
        method: "PUT",
        body: data,
      }),
      invalidatesTags: (result, error, { vendorId }) => [
        { type: "VendorPermissions", id: vendorId },
        "VendorPermissions",
        "Permissions",
      ],
    }),

    bulkUpdateVendorPermissions: builder.mutation<
      ApiResponse<BulkUpdatePermissionsResponse>,
      BulkUpdatePermissionsRequest
    >({
      query: (body) => ({
        url: "/offers/admin/vendor-permissions/bulk-update",
        method: "POST",
        body,
      }),
      invalidatesTags: ["VendorPermissions", "Permissions"],
    }),

    resetVendorPermissions: builder.mutation<
      ApiResponse<VendorPermissions>,
      string
    >({
      query: (vendorId) => ({
        url: `/offers/admin/vendor-permissions/${vendorId}/reset`,
        method: "POST",
      }),
      invalidatesTags: (result, error, vendorId) => [
        { type: "VendorPermissions", id: vendorId },
        "VendorPermissions",
        "Permissions",
      ],
    }),

    // =============================
    // ADMIN ENDPOINTS - REPORTING
    // =============================

    getOfferPerformanceReport: builder.query<
      ApiResponse<OfferPerformanceReport[]>,
      OfferPerformanceFilters
    >({
      query: (params) => ({
        url: "/offers/admin/reports/performance",
        method: "GET",
        params,
      }),
      providesTags: ["Reports"],
    }),

    getTopPerformingOffers: builder.query<
      ApiResponse<OfferPerformanceReport[]>,
      TopPerformingOffersFilters
    >({
      query: (params) => ({
        url: "/offers/admin/reports/top-performing",
        method: "GET",
        params,
      }),
      providesTags: ["Reports"],
    }),

    getOfferTypeDistribution: builder.query<
      ApiResponse<Record<OfferType, number>>,
      { vendorId?: string }
    >({
      query: (params) => ({
        url: "/offers/admin/reports/type-distribution",
        method: "GET",
        params,
      }),
      providesTags: ["Reports"],
    }),

    // =============================
    // VENDOR ENDPOINTS
    // =============================

    createVendorOffer: builder.mutation<ApiResponse<Offer>, CreateOfferRequest>({
      query: (body) => ({
        url: "/offers/vendor",
        method: "POST",
        body,
      }),
      invalidatesTags: ["VendorOffer"],
    }),

    getVendorOffers: builder.query<PaginatedResponse<Offer>, OfferFilters>({
      query: (params) => ({
        url: "/offers/vendor",
        method: "GET",
        params,
      }),
      providesTags: ["VendorOffer"],
    }),

    getVendorOfferById: builder.query<ApiResponse<Offer>, string>({
      query: (offerId) => ({
        url: `/offers/vendor/${offerId}`,
        method: "GET",
      }),
      providesTags: (result, error, id) => [{ type: "VendorOffer", id }],
    }),

    createVendorVoucher: builder.mutation<
      ApiResponse<Offer>,
      CreateVendorVoucherRequest
    >({
      query: (body) => ({
        url: "/offers/vendor/voucher",
        method: "POST",
        body,
      }),
      invalidatesTags: ["VendorOffer"],
    }),

    updateVendorOffer: builder.mutation<
      ApiResponse<Offer>,
      { offerId: string; data: Partial<CreateOfferRequest> }
    >({
      query: ({ offerId, data }) => ({
        url: `/offers/vendor/${offerId}`,
        method: "PUT",
        body: data,
      }),
      invalidatesTags: (result, error, { offerId }) => [
        { type: "VendorOffer", id: offerId },
        "VendorOffer",
      ],
    }),

    deactivateVendorOffer: builder.mutation<ApiResponse<Offer>, string>({
      query: (offerId) => ({
        url: `/offers/vendor/${offerId}/deactivate`,
        method: "PATCH",
      }),
      invalidatesTags: (result, error, offerId) => [
        { type: "VendorOffer", id: offerId },
        "VendorOffer",
      ],
    }),

    getVendorOfferAnalytics: builder.query<
      ApiResponse<OfferAnalytics[]>,
      string
    >({
      query: (offerId) => ({
        url: `/offers/vendor/analytics/${offerId}`,
        method: "GET",
      }),
      providesTags: ["Analytics"],
    }),

    getVendorPermissionsInfo: builder.query<
      ApiResponse<VendorPermissions>,
      void
    >({
      query: () => ({
        url: "/offers/vendor/permissions",
        method: "GET",
      }),
      providesTags: ["Permissions"],
    }),

    getVendorOffersSummary: builder.query<
      ApiResponse<VendorOffersSummary>,
      void
    >({
      query: () => ({
        url: "/offers/vendor/summary",
        method: "GET",
      }),
      providesTags: ["VendorOffer", "Reports"],
    }),

    getVendorTopPerformingOffers: builder.query<
      ApiResponse<OfferPerformanceReport[]>,
      TopPerformingOffersFilters
    >({
      query: (params) => ({
        url: "/offers/vendor/reports/top-performing",
        method: "GET",
        params,
      }),
      providesTags: ["Reports"],
    }),

    getVendorOfferTypeDistribution: builder.query<
      ApiResponse<Record<OfferType, number>>,
      void
    >({
      query: () => ({
        url: "/offers/vendor/reports/type-distribution",
        method: "GET",
      }),
      providesTags: ["Reports"],
    }),

    // =============================
    // CUSTOMER ENDPOINTS
    // =============================

    getAvailableOffers: builder.query<PaginatedResponse<Offer>, OfferFilters>({
      query: (params) => ({
        url: "/offers",
        method: "GET",
        params,
      }),
      providesTags: ["Offer"],
    }),

    applyVoucher: builder.mutation<
      ApiResponse<ApplyVoucherResponse>,
      ApplyVoucherRequest
    >({
      query: (body) => ({
        url: "/offers/apply-voucher",
        method: "POST",
        body,
      }),
    }),

    getCountdownOffers: builder.query<ApiResponse<Offer[]>, void>({
      query: () => ({
        url: "/offers/countdown",
        method: "GET",
      }),
      providesTags: ["Offer"],
    }),

    getBuyXGetYOffersCustomer: builder.query<ApiResponse<Offer[]>, void>({
      query: () => ({
        url: "/offers/buy-x-get-y",
        method: "GET",
      }),
      providesTags: ["Offer"],
    }),

    validateOffer: builder.mutation<
      ApiResponse<ValidateOfferResponse>,
      ValidateOfferRequest
    >({
      query: (body) => ({
        url: "/offers/validate",
        method: "POST",
        body,
      }),
    }),

    getUserOfferUsageHistory: builder.query<
      PaginatedResponse<OfferUsage>,
      UsageHistoryFilters
    >({
      query: (params) => ({
        url: "/offers/usage-history",
        method: "GET",
        params,
      }),
      providesTags: ["UsageHistory"],
    }),

    // =============================
    // OFFER USAGE ENDPOINTS
    // =============================

    recordOfferUsage: builder.mutation<
      ApiResponse<{ message: string }>,
      RecordOfferUsageRequest
    >({
      query: (body) => ({
        url: "/offers/usage/record",
        method: "POST",
        body,
      }),
      invalidatesTags: ["UsageHistory", "Analytics", "Offer"],
    }),

    getOfferUsageStats: builder.query<
      ApiResponse<OfferUsageStats>,
      string
    >({
      query: (offerId) => ({
        url: `/offers/usage/stats/${offerId}`,
        method: "GET",
      }),
      providesTags: (result, error, offerId) => [
        { type: "Analytics", id: offerId }
      ],
    }),
  }),
});

// =============================
// EXPORT HOOKS
// =============================

export const {
  // Public
  useGetPublicOffersQuery,
  useGetFlashSalesQuery,
  useGetBuyXGetYOffersQuery,
  
  // Admin - Offer Management
  useCreateOfferMutation,
  useGetAllOffersQuery,
  useGetOfferByIdQuery,
  useUpdateOfferMutation,
  useDeleteOfferMutation,
  useCreateFlashSaleMutation,
  useCreateSystemVoucherMutation,
  useApproveVendorOfferMutation,
  useGetOfferAnalyticsQuery,
  useGetAllOfferAnalyticsQuery,
  
  // Admin - Vendor Permission Management
  useGetAllVendorPermissionsQuery,
  useGetVendorPermissionStatsQuery,
  useSearchVendorsForPermissionsQuery,
  useGetVendorPermissionsQuery,
  useUpdateVendorPermissionsMutation,
  useBulkUpdateVendorPermissionsMutation,
  useResetVendorPermissionsMutation,
  
  // Admin - Reporting
  useGetOfferPerformanceReportQuery,
  useGetTopPerformingOffersQuery,
  useGetOfferTypeDistributionQuery,
  
  // Vendor
  useCreateVendorOfferMutation,
  useGetVendorOffersQuery,
  useGetVendorOfferByIdQuery,
  useCreateVendorVoucherMutation,
  useUpdateVendorOfferMutation,
  useDeactivateVendorOfferMutation,
  useGetVendorOfferAnalyticsQuery,
  useGetVendorPermissionsInfoQuery,
  useGetVendorOffersSummaryQuery,
  useGetVendorTopPerformingOffersQuery,
  useGetVendorOfferTypeDistributionQuery,
  
  // Customer
  useGetAvailableOffersQuery,
  useApplyVoucherMutation,
  useGetCountdownOffersQuery,
  useGetBuyXGetYOffersCustomerQuery,
  useValidateOfferMutation,
  useGetUserOfferUsageHistoryQuery,
  } = offerApi;