import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/publicnavbar/Navbar";
import ReduxProvider from "@/context/ReduxProvider";
import MobileBottomNav from "@/components/movilebottomnav/MobileBottomNav";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Toaster } from "sonner";
config.autoAddCss = false;

// Primary font for body text, product info, prices
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700"],
});

// Heading font for titles, navigation, CTAs
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "FinixMart - Multi Vendor E-commerce Platform",
  description: "Generated by Rayhan Sardar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${plusJakartaSans.variable}`}>
      <head>
        {/* FontAwesome CDN as backup */}
        <link
          rel="stylesheet"
          href="https://c.webfontfree.com/c.css?f=OTS-derived-font"
        />

        {/* FontAwesome CDN as backup */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </head>
      <body className="font-sans  antialiased">
        <ReduxProvider>
          <Navbar />
          {children}
          <Toaster 
          position="top-right"
          toastOptions={{
            classNames: {
              toast: 'group toast',
              title: 'text-sm font-semibold',
              description: 'text-sm opacity-90',
              actionButton: 'group-[.toast]:bg-primary group-[.toast]:text-primary-foreground',
              cancelButton: 'group-[.toast]:bg-muted group-[.toast]:text-muted-foreground',
              success: 'bg-green-50 border-green-200 text-green-900',
              error: 'bg-red-50 border-red-200 text-red-900',
              warning: 'bg-yellow-50 border-yellow-200 text-yellow-900',
              info: 'bg-blue-50 border-blue-200 text-blue-900',
            },
          }}
        />
          <MobileBottomNav />
        </ReduxProvider>
      </body>
    </html>
  );
}
